//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineStore.Website.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статьи.
        /// </summary>
        public static string ArticleCarouselTitle {
            get {
                return ResourceManager.GetString("ArticleCarouselTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уход и Содержание.
        /// </summary>
        public static string CareAndMaintaince {
            get {
                return ResourceManager.GetString("CareAndMaintaince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корзина пуста..
        /// </summary>
        public static string CartEmpty {
            get {
                return ResourceManager.GetString("CartEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        public static string CategoriesListTitle {
            get {
                return ResourceManager.GetString("CategoriesListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все товары.
        /// </summary>
        public static string CategoryAll {
            get {
                return ResourceManager.GetString("CategoryAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цефалотус.
        /// </summary>
        public static string Cephalotus {
            get {
                return ResourceManager.GetString("Cephalotus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, проверьте электронную почту и подтвердите аккаунт!.
        /// </summary>
        public static string CheckYourEmail {
            get {
                return ResourceManager.GetString("CheckYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить аккаунт.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, что-то пошло не так....
        /// </summary>
        public static string ConfirmEmailError {
            get {
                return ResourceManager.GetString("ConfirmEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт подтвержден!.
        /// </summary>
        public static string ConfirmEmailSucceded {
            get {
                return ResourceManager.GetString("ConfirmEmailSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, перейдите на страницу.
        /// </summary>
        public static string ConfirmEmailSuccededBody {
            get {
                return ResourceManager.GetString("ConfirmEmailSuccededBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не совпадает!.
        /// </summary>
        public static string ConfirmPasswordInvalid {
            get {
                return ResourceManager.GetString("ConfirmPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите введенный пароль!.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты:.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to бел. руб..
        /// </summary>
        public static string CurrencyName {
            get {
                return ResourceManager.GetString("CurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дарлингтония Калифорнийская.
        /// </summary>
        public static string DarlingtoniaCalifornica {
            get {
                return ResourceManager.GetString("DarlingtoniaCalifornica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Венерина Мухоловка.
        /// </summary>
        public static string DionaeaMuscipula {
            get {
                return ResourceManager.GetString("DionaeaMuscipula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет аккаунта?.
        /// </summary>
        public static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Росянка.
        /// </summary>
        public static string Drosera {
            get {
                return ResourceManager.GetString("Drosera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для продолжение регистрации, пожалуйста, нажмите на кнопку ниже, чтобы подтвердить аккаунт:.
        /// </summary>
        public static string EmailConfirmationBody {
            get {
                return ResourceManager.GetString("EmailConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venusflytrap.com - Подтверждение аккаунта..
        /// </summary>
        public static string EmailConfirmationSubject {
            get {
                return ResourceManager.GetString("EmailConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите корректный адрес электронной почты!.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин или пароль!.
        /// </summary>
        public static string EmailOrPasswordInvalid {
            get {
                return ResourceManager.GetString("EmailOrPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите email.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите адрес электронной почты!.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите файл....
        /// </summary>
        public static string FilenamePlaceholder {
            get {
                return ResourceManager.GetString("FilenamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следите за нами в социальных сетях:.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Галерея.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На главную.
        /// </summary>
        public static string GoToHome {
            get {
                return ResourceManager.GetString("GoToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venusflytrap.com - онлайн-магазин хищных растений в Минске!.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        public static string ImageFilename {
            get {
                return ResourceManager.GetString("ImageFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина имени файла должна быть от 1-250 символов!.
        /// </summary>
        public static string ImageFilenameSizeError {
            get {
                return ResourceManager.GetString("ImageFilenameSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Важно!.
        /// </summary>
        public static string ImportantBadge {
            get {
                return ResourceManager.GetString("ImportantBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упс... Внутренняя ошибка сервера. Серверу не удалось выполнить ваш запрос. Пожалуйста, повторите запрос позже!.
        /// </summary>
        public static string InternalServerErrorMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venusflytrap.com - Внутренняя ошибка сервера.
        /// </summary>
        public static string InternalServerErrorTitle {
            get {
                return ResourceManager.GetString("InternalServerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный файл не является изображением!.
        /// </summary>
        public static string IsNotImage {
            get {
                return ResourceManager.GetString("IsNotImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык!.
        /// </summary>
        public static string LanguageRequired {
            get {
                return ResourceManager.GetString("LanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venusflytrap - Главная страница сайта. На данной странице вы можете просмотреть категории хищных растений..
        /// </summary>
        public static string MainPageDescription {
            get {
                return ResourceManager.GetString("MainPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to хищные растения, хищные растения в Минске, Минск, хищные, растения, росянка, мухоловка, венерина мухоловка.
        /// </summary>
        public static string MainPageKeywords {
            get {
                return ResourceManager.GetString("MainPageKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование (А - Я).
        /// </summary>
        public static string NameAscending {
            get {
                return ResourceManager.GetString("NameAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование (Я - А).
        /// </summary>
        public static string NameDescending {
            get {
                return ResourceManager.GetString("NameDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя.
        /// </summary>
        public static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя!.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина имени должна быть от 1-100 символов!.
        /// </summary>
        public static string NameSizeError {
            get {
                return ResourceManager.GetString("NameSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Непентес.
        /// </summary>
        public static string Nepenthes {
            get {
                return ResourceManager.GetString("Nepenthes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без сортировки.
        /// </summary>
        public static string NoSort {
            get {
                return ResourceManager.GetString("NoSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упс... Данная страница не найдена. Используйте поиск или вернитесь на главную страницу..
        /// </summary>
        public static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venusflytrap.com - Страница не найдена или не существует.
        /// </summary>
        public static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to из.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venusflytrap.com - &lt;strong&gt;первый интернет - магазин хищных растений &lt;/strong&gt; в Минске! В нашем магазине вы можете приобрести &lt;strong&gt;более &lt;span class=&quot;text-danger&quot;&gt;200&lt;/span&gt; редких сортов хищных растений со всего мира&lt;/strong&gt;, а также абсолютно всё, что требуется для выращивания: специализированные субстраты, компоненты субстрата, горшки, дистиллированная вода, препараты и многое другое!.
        /// </summary>
        public static string OnlineStoreFooterAbout {
            get {
                return ResourceManager.GetString("OnlineStoreFooterAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать:.
        /// </summary>
        public static string PageSizeTitle {
            get {
                return ResourceManager.GetString("PageSizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина пароля должна быть от 8 - 64 символов, содержать буквы англ. алфавита, цифры и специальные символы и не должен содержать пробелов или эмодзи..
        /// </summary>
        public static string PasswordHelp {
            get {
                return ResourceManager.GetString("PasswordHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль!.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина пароля должна быть в диапазоне от 8 до 64 символов!.
        /// </summary>
        public static string PasswordSizeError {
            get {
                return ResourceManager.GetString("PasswordSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string Patronymic {
            get {
                return ResourceManager.GetString("Patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите отчество.
        /// </summary>
        public static string PatronymicPlaceholder {
            get {
                return ResourceManager.GetString("PatronymicPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина отчества должна быть от 1-150 символов!.
        /// </summary>
        public static string PatronymicSizeError {
            get {
                return ResourceManager.GetString("PatronymicSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата и Доставка.
        /// </summary>
        public static string PaymentAndDelivery {
            get {
                return ResourceManager.GetString("PaymentAndDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер моб. телефона.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер моб. телефона введен некорректно!.
        /// </summary>
        public static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходим номер моб. телефона!.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жирянка.
        /// </summary>
        public static string Pinguicula {
            get {
                return ResourceManager.GetString("Pinguicula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, попробуйте еще раз.
        /// </summary>
        public static string PleaseTry {
            get {
                return ResourceManager.GetString("PleaseTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена (по возрастанию).
        /// </summary>
        public static string PriceAscending {
            get {
                return ResourceManager.GetString("PriceAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена (по убыванию).
        /// </summary>
        public static string PriceDescending {
            get {
                return ResourceManager.GetString("PriceDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товары.
        /// </summary>
        public static string ProductCarouselTitle {
            get {
                return ResourceManager.GetString("ProductCarouselTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venusflytrap - Каталог продуктов сайта. На данной странице вы можете просмотреть категории хищных растений. Искать и фильтровать продукты каталога..
        /// </summary>
        public static string ProductCatalogPageDescription {
            get {
                return ResourceManager.GetString("ProductCatalogPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to хищные растения, хищные растения в Минске, Минск, хищные, растения, росянка, мухоловка, венерина мухоловка, каталог, каталог хищных растений.
        /// </summary>
        public static string ProductCatalogPageKeywords {
            get {
                return ResourceManager.GetString("ProductCatalogPageKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venusflytrap.com - Каталог продуктов..
        /// </summary>
        public static string ProductCatalogTitle {
            get {
                return ResourceManager.GetString("ProductCatalogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Саррацения.
        /// </summary>
        public static string Sarracenia {
            get {
                return ResourceManager.GetString("Sarracenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по имени и цене....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venusflytrap.com - Вход в аккаунт.
        /// </summary>
        public static string SignInPageDescription {
            get {
                return ResourceManager.GetString("SignInPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venusflytrap.com войти, войти, вход.
        /// </summary>
        public static string SignInPageKeywords {
            get {
                return ResourceManager.GetString("SignInPageKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venusflytrap.com - Регистрация.
        /// </summary>
        public static string SignUpPageDescription {
            get {
                return ResourceManager.GetString("SignUpPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venusflytrap.com зарегистрироваться, зарегистрироваться, регистрация.
        /// </summary>
        public static string SignUpPageKeywords {
            get {
                return ResourceManager.GetString("SignUpPageKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировать по:.
        /// </summary>
        public static string SortOrder {
            get {
                return ResourceManager.GetString("SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акции.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акция!.
        /// </summary>
        public static string StockBadge {
            get {
                return ResourceManager.GetString("StockBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите фамилию.
        /// </summary>
        public static string SurnamePlaceholder {
            get {
                return ResourceManager.GetString("SurnamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите фамилию!.
        /// </summary>
        public static string SurnameRequired {
            get {
                return ResourceManager.GetString("SurnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина фамилии должна быть от 1-150 символов! .
        /// </summary>
        public static string SurnameSizeError {
            get {
                return ResourceManager.GetString("SurnameSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким email уже существует!.
        /// </summary>
        public static string UserExist {
            get {
                return ResourceManager.GetString("UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пузырчатка.
        /// </summary>
        public static string Utricularia {
            get {
                return ResourceManager.GetString("Utricularia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
    }
}
